# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    consoleLogLevel = 3;
    extraModulePackages = [ ];

    initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
    initrd.kernelModules = [ "amdgpu" ];
    initrd.verbose = false;

    kernelModules = [ "amdgpu" ];
    kernelPackages = pkgs.linuxPackages_latest; # force to use the last kernel (not necessary)
    kernelParams = [ "quiet" "splash" "boot.shell_on_fail" "udev.log_priority=3" "rd.systemd.show_status=auto" ];

    loader.systemd-boot.enable = true;
    loader.efi.canTouchEfiVariables = true;

    # Hide the OS choice for bootloaders.
    # It's still possible to open the bootloader list by pressing any key
    # It will just not appear on screen unless a key is pressed
    loader.timeout = 0;

    # Hide verbose logs at startup
    plymouth.enable = true;
  };
  
  # Improve SSD management
  services.fstrim.enable = true;

  # Mount drives
  fileSystems."/" =           { device = "/dev/disk/by-uuid/f4a796ae-a25d-4d46-a8ca-c36730305f70"; fsType = "ext4"; };
  fileSystems."/media/Jeux" = { device = "/dev/disk/by-uuid/44327937-4697-4939-b15f-de6a7580ca9d"; fsType = "ext4"; };
  fileSystems."/boot" =       { device = "/dev/disk/by-uuid/5BE0-6CB4"; fsType = "vfat"; options = [ "fmask=0077" "dmask=0077" ]; };
  swapDevices = [ 
    { device = "/dev/disk/by-uuid/593f3ccc-3575-4074-8fcf-e21b6a4616ca"; }
  ];

  # Fix scanner instrument search
  hardware.sane = {
    enable = true;
    extraBackends = [ pkgs.sane-airscan ];
    disabledDefaultBackends = [ "escl" ];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp11s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.amdgpu.opencl.enable = true; # Fix for Davinci resolve
  
  #hardware.bluetooth.enable = true; # enables support for Bluetooth
  #hardware.bluetooth.powerOnBoot = true; # powers up the default Bluetooth controller on boot
   
  hardware.graphics = { 
    enable = true;
    enable32Bit = true;
    
    # enable Vulkan support for 32-bit & 64-bit applications
    extraPackages   = [ pkgs.amdvlk ];
    extraPackages32 = [ pkgs.driversi686Linux.amdvlk ];
  };

  environment.variables = {
    # Force radv
    AMD_VULKAN_ICD = "RADV";
    VK_ICD_FILENAMES = "/run/opengl-driver/share/vulkan/icd.d/radeon_icd.x86_64.json";
  };
}
